language: objective-c
os: osx
osx_image: xcode8.3
sudo: required
branches:
  only:
  - master
  - "/^v[\\d\\.]+$/"
script:
- make build
before_deploy:
- make build
- make dist
deploy:
  provider: releases
  api_key:
    secure: j2eFTzFP1u2zXLEkZtgRiIwreStWZKccli5lAG2jC8Mk0a29yt01AD7VBI5piR0jelEhxI3IUHYOoC9IuhIwkhQx+MpYUwKQ1kHrExzmv6Pf6AMSUhDnFYKYQ5vuLv3DzIcMKBxKRoh+s8HXerk8Sv2l0hI+VMw5eOTNYmXyr3+OMprgIqZZSepTo30RS3X0vDo5VqEiKJp+JQk7ZpfuGWJOIGnKz7fw41X7BJK23MFN+Z3lLFHL9LSnebSOxm+mX6KaVSfZqG77upIjJkXJbGYzFdgqgOwWS7RqtYJSsoJS5XBCtE96IT5hCXhB+DUYIqSv4dTesnr7JUJfupwDG2CDNYG/UT3amX4endjc2G/oongKD6wNVhVPj09DTVL0lfaM7NBlB0MvEWjG7ntqeu7fAUYa5KKKNAHFjgMbZwd1zHLRK9ibNsvBCCenx+Q3Mjr9dL/69d7C3qYr6Jy733PmayJYlH2Zdsu1g3FFTQ1SiJJxkFQP4sNGyPBk3tpzLv2oZWhETV893QqpEQJmxsYVHZ3e4PslbKISqQMrUFnQE5vtImcPWNaOqfWPYqbd4QA2hd0BjecgKXTdXkvcmLQ8T7oK0J82q++wvs+2YWcodn2sl4feDH1o1ObLAcojCYWuBgT0rUbFf+9e/s6KYLvgsgsH9YXUa8ksEYChvT8=
  skip_cleanup: true
  file_glob: true
  file: build/*.zip
  on:
    tags: true
    repo: potsbo/KeyType
