language:  objective-c
os:        osx
osx_image: xcode8.3  # OS X 10.12 (https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)

sudo: required

branches:
  only:
    - master
    - /^v[\d\.]+$/

script:
  - make build

before_deploy:
  - make build
  - make dist
