name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@1.0
      with:
        xcode-version: 11.6
    - name: Install xcpretty
      run: gem install xcpretty
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: make build | xcpretty
    - name: Test
      run: make test | xcpretty
    - name: Upload coverage information
      run: bash <(curl -s https://codecov.io/bash)
    - name: Dist
      run: make dist
